### PR TITLE
Correct rfid & weight timer

### LINKED ISSUE #35: RFID and Weight timing wrong in master branch
The rfid has to read for 120s or until it has a positive read.
There should be a 60 s gap to allow creature to get into the box.

See branch rfid and weight

### PR DESCRIPTION
**Pull request by jw2476**
Fine tuned the time periods for maximum, accurate measurements

Fixes #35

### CODE REVIEW

**Comment by jw2476** [comment]
@Gabrielkyne has this code been tested?

**Comment by jw2476** [comment]
Is all of this needed? You could have passed in a time period in the class instantiation and set timeout to be this new parameter

**Comment by Gabrielkyne** [comment]
same difference ... more visible if on call on read.

Go with it I think there is only a line of code in it if that

**Comment by jw2476** [comment]
Upon further review of the code I realized that this wouldn't work anyway as the timeout specified in the __init__ function in rfid.py would overide the time specified, so I made the changes listed in my previous message in the branch correct-rfid-and-weight-timer, there is a pull request for it to be merged in to this branch.

**Pull request merged**
