### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by jw2476**
Added documentation under the docs folder, uses sphinx and restructured text, markdown is possible but not implemented so let me know if you would like it. requirements.txt has been updated, but I don't think the Pipfile has if you could have a look at that @sebbacon that would be great.

Documentation is viewable [here](https://hogpi.readthedocs.io/en/latest/)

### CODE REVIEW

**Comment by sebbacon** [comment]
Looks good, apart from I don't understand what you were trying to do with the Pipfile / requirements.txt so can't comment on that:

What package were you adding for the install and why?

Why were you doing this via a Pipfile?

**Comment by jw2476** [comment]
The documentation uses sphinx and the sphinx readthedocs theme. They both add a ton of dependencies and I wanted them in requirements.txt so everyone can work on the docs. I mixed this repository up with a different one, and that one uses pipenv so I used it. Sorry, my mistake will delete them now

**Comment by sebbacon** [comment]
Exactly how did you build the list of extra dependencies required by sphinx?

**Comment by jw2476** [comment]
pip freeze > requirements.txt

**Comment by sebbacon** [comment]
Ok. So the workflow I recommend (this is a rubbish part of Python by the way, with too many options about how to do it) is to use pip-tools.  Then it's easy to see *why* you have each dependency.

1. Install pip tools `pip install pip-tools`.
2. When you install a new package (e.g. `sphinx`), add it to `requirements.in`
3. Run `pip-compile` to generate a new `requirements.txt`
4. Add both in a single commit 
5. Ig and when you want to ensure your current virtual environment matches `requirements.txt` exactly, run `pip-compile` (if you just do `pip install -r requirements.txt` you always *add* packages but never *remove* redundant ones)

Using this system, if sphinx itself pulls in 11 new packages, you can distinguish between which package is there for which reason (and if we stopped using sphinx it would be easy to remove redundant packages again).

This keeps your virtualenv clean and makes it less likely you'll have unused packages that eventually become security risks, and/or strange package conflicts in the future.

Does that make sense?

**Comment by jw2476** [comment]
Thanks for clearing that up.

**Comment by jw2476** [comment]
For adding the package to requirements.in, would I be able to use pip list
> requirements.in

**Comment by jw2476** [comment]
Wait ignore that I just worked it out

**Comment by jw2476** [comment]
Shall I merge this into master

**Pull request merged**
